### ISSUE TITLE
recipes-bsp/u-boot/u-boot-exynos-extlinux.bb

### ISSUE THREAD

**Issue by blithe2015** [hyyoxhk/meta-exynos#1]
Unable to get checksum for u-boot-exynos-extlinux SRC_URI entry boot.scr.cmd: file could not be found

 是更改SRC_URI = "file://boot.scr.cmd"  -> SRC_URI = "file://boot.cmd" 

inherit kernel-arch extlinux-config -> inherit kernel-arch uboot-extlinux-config

**Comment by hyyoxhk** [comment]
请使用git reset --hard e6c588a2c9ca700cb4e751c9809db8eabee9469c命令回退到v1.0 tag上可以编译，新的特性我还没时间上传
